GET http://localhost:3000/orders

###
GET http://localhost:3000/orders/919a46d3-62aa-41d9-9b02-ccb8ecd2fbe4

###

POST http://localhost:3000/orders
Content-Type: application/json

{
  "amount": 10000
}
###

PATCH  http://localhost:3000/orders/bf2a3095-fd2e-4f03-8faa-8f6dd848cbb9
Content-Type: application/json

{
  "amount": 22000,
  "status": "approved"
}
###
DELETE  http://localhost:3000/orders/33dcd148-2dec-4e68-8994-2fffa34cd7dd
